<?php

use App\Session;

?>

<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Site de locations entre particuliers">

    <!-- Feuilles de styles -->
    <link rel="stylesheet" href="../assets/css/reset.css">
    <link rel="stylesheet" href="../assets/css/style.css">

    <title><?php echo $title ?></title>
</head>

<body>
    <div id="top-container">
        <!-- Logo de l'application -->
        <div class="logo">
            <a href="/">AIRBNB</a>
        </div>

        <?php if ($auth::isAuth()): ?>
            <!-- Informations de l'utilisateur authentifié -->
            <div class="user-info">
                <!-- Affiche le prénom de l'utilisateur -->
                <div class="user-name">Bonjour <?php echo Session::get(Session::USER)->getfirstName(); ?></div>

                <!-- Affiche le mode de l'utilisateur (Propriétaire ou Utilisateur) -->
                <div class="user-mode">
                    Mode : <?php echo $auth::isOwner() ? 'Propriétaire' : 'Utilisateur'; ?>
                </div>
            </div>

            <!-- Liens spécifiques aux actions d'un utilisateur authentifié -->
            <div class="user-actions">
                <ul>
                    <!-- Lien vers les réservations -->
                    <li><a id="reservations-button" href="/reservations">Mes réservations</a></li>
                    <!-- Lien pour se déconnecter -->
                    <li><a id="signout-button" href="/sign-out">Se déconnecter</a></li>
                </ul>
            </div>

        <?php else: ?>
            <!-- Liens pour les utilisateurs non authentifiés -->
            <div class="auth-actions">
                <!-- Lien pour créer un compte -->
                <a id="signup-button" href="/sign-up">Créer un compte</a>
                <!-- Lien pour se connecter -->
                <a id="signin-button" href="/sign-in">Se connecter</a>
            </div>
        <?php endif; ?>
    </div>

    <div id="main-container">
        <!-- Contenu de la page -->