<?php

use App\Model\Entity\User;
use App\Session;

?>

<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Site de locations entre particuliers">

    <!-- Feuilles de styles -->
    <link rel="stylesheet" href="../assets/css/reset.css">
    <link rel="stylesheet" href="../assets/css/style.css">

    <title><?php echo $title ?></title>
</head>

<body>

    <div id="top-container">
        <?php if ($auth::isAuth()): ?>
            <div>
                <div class="logo">
                    <a href="/">AIRBNB</a>
                </div>
                <div>Bonjour <?php echo Session::get(Session::USER)->getfirstName() ?></div>
                <div>Id : <?php echo Session::get(Session::USER)->getId() ?></div>
                <div>
                    Mode :
                    <?php if (Session::get('user')->getTypeAccount() == User::ROLE_OWNER): ?>
                        Propriétaire
                    <?php elseif (Session::get('user')->getTypeAccount() == User::ROLE_USER): ?>
                        Utilisateur
                    <?php endif; ?>
                </div>
            </div>
            <div>
                <ul>
                    <?if($auth::isOwner()): ?>
                        <li><a href="/rentals/user/<?php echo(Session::get('user')->getId()) ?>">Mes locations</a></li>
                    <?php endif; ?>
                    <li><a href="/reservations">Mes réservations</a></li>
                </ul>
            </div>
            <div>
                <a id="signout-button" href="/sign-out">Se déconnecter</a>
            </div>
        <?php else: ?>
            <div id="top-button">
                <div>
                    <a id="signup-button" href="/sign-up">Créer un compte</a>
                </div>
                <div>
                    <a id="signin-button" href="/sign-in">Se connecter</a>
                </div>
            </div>
        <?php endif ?>
    </div>