<!-- Page de connexion -->

<div>
    <a href="<?php echo $_SERVER['HTTP_REFERER']; ?>">↩ Retour</a>
</div>

<h1>Se connecter</h1>


<div class="container-body">

    <!-- Gestion des messages d'erreur -->
    <?php if (isset($_GET['error'])): ?>
        <div class="error-message">
            <p class="error"><?php echo $_GET['error'] ?></p>
        </div>
    <?php endif; ?>

    <!-- Formulaire de connexion -->
    <form action="/sign-in" method="post">
        <div>
            <label for="email">Adresse email : </label>
            <input type="email" id="email" name="email" required>
        </div>
        <div>
            <label for="password">Mot de passe : </label>
            <input type="password" id="password" name="password" required>
        </div>
        <div class="button">
            <button type="submit">Se connecter</button>
        </div>
    </form>
</div>