<!-- Page de création d'un compte utilisateur ou annoceur -->

<?php

use App\Model\Entity\User;

?>

<div>
    <a href="/">↩ Retour</a>
</div>

<h1>Créer mon compte</h1>

<div class="container-body">

    <!-- Gestion des messages d'erreur -->
    <?php if ( isset( $_GET[ 'error' ] ) ): ?>
        <div class="error-message">
            <p class="error"><?php echo $_GET[ 'error' ] ?></p>
        </div>
    <?php endif; ?>

    <!-- Formulaire de création d'un compte -->
    <form action="/sign-up" id="form-create-user" method="post">
        <fieldset>
            <legend>Informations personnelles</legend>
            <div>
                <label for="firstName">Prénom : </label>
                <input type="text" id="firstName" name="firstName">
            </div>
            <div>
                <label for="lastName">Nom : </label>
                <input type="text" id="lastName" name="lastName" required>
            </div>
        </fieldset>
        <fieldset>
            <legend>Informations de connexion</legend>
            <div>
                <label for="email">Adresse email : </label>
                <input type="email" id="email" name="email" required>
            </div>
            <div>
                <label for="password">Mot de passe : </label>
                <input type="password" id="password" name="password" required>
            </div>
        </fieldset>
        <fieldset>
            <legend>Type de compte</legend>
            <div>
                <select name="typeAccount" id="typeAccount">
                    <option value=<?php echo User::ROLE_OWNER ?>>Annonceur</option>
                    <option value=<?php echo User::ROLE_USER ?>>Utilisateur</option>
                </select>
            </div>
        </fieldset>
        <div class="button">
            <button type="submit">Créer mon compte</button>
        </div>
    </form>
</div>