<!-- Page de création d'une location par un annonceur -->

<h1>Créer une location</h1>

<div id="container-body">
    <form action="/rentals/add" id="form-create-rental" method="post" enctype="multipart/form-data">

        <!-- Gestion des messages d'erreur -->
        <?php if (isset($_GET['error'])): ?>
            <div class=" error-message ">
                <p class=" error"><?php echo $_GET['error'] ?></p>
            </div>
        <?php endif; ?>

        <fieldset>
            <legend>Titre de la location</legend>
            <div>
                <label for="title">Titre : </label>
                <input type="text" name="title" id="title">
            </div>
        </fieldset>
        <fieldset>
            <legend>Informations sur la location</legend>
            <div>
                <label for="price">Prix : </label>
                <input type="number" name="price" id="price">
            </div>
            <div>
                <label for="surface">Surface : </label>
                <input type="number" name="surface" id="surface">
            </div>
            <div class="rental-description">
                <label for="description">Description : </label>
                <textarea name="description" id="description"></textarea>
            </div>
            <div>
                <label for="beddings">Nombre de couchage : </label>
                <input type="number" name="beddings" id="beddings">
            </div>
            <div>
                <label for="typeLogement">Type de logement : </label>
                <select name="typeLogement_id" id="typeLogement">
                    <?php foreach ($types as $type):
                        echo "<option value='" . $type->getId() . "'>" . $type->getName() . "</option>";
                    endforeach; ?>
                </select>
            </div>
        </fieldset>
        <fieldset>
            <legend>Adresse de la location</legend>
            <div>
                <label for="city">Ville :</label>
                <input type="text" name="city" id="city">
            </div>
            <div>
                <label for="country">Pays :</label>
                <input type="text" name="country" id="country">
            </div>
        </fieldset>
        <fieldset>
            <legend>Equipements disponibles</legend>
            <div class="equipments-div">
                <?php foreach ($equipments as $equipment): ?>
                    <div>
                        <label for='equipments[]'><?php echo $equipment->getName(); ?></label>
                        <input type='checkbox' name='equipments[]' value='<?php echo $equipment->getId(); ?>'>
                    </div>
                <?php endforeach; ?>
            </div>
        </fieldset>
        <fieldset>
            <legend>Photos de la location</legend>
            <div>
                <label for="image">Photos : </label>
                <input type="file" name="image" id="image">
            </div>
        </fieldset>
        <div class="button">
            <button type="submit">Ajouter</button>
        </div>
    </form>
</div>