<?php use App\Model\Repository\RepoManager; ?>

<div>
    <a href="/">🔙 Retour</a>
</div>

<h1>Créer une location</h1>

<form action="/rentals/add" id="form-create-rental" method="post">

    <!-- gestion des messages d'erreur -->
    <?php

    if (isset($_GET['error'])): ?>
        <p class="error"><?php echo $_GET['error'] ?></p>
    <?php endif; ?>

    <div>
        <label for="title">Titre :</label>
        <input type="text" name="title" id="title">
    </div>
    <div>
        <label for="price">Prix :</label>
        <input type="number" name="price" id="price">
    </div>
    <div>
        <label for="surface">Surface</label>
        <input type="number" name="surface" id="surface">
    </div>
    <div>
        <label for="description">Description :</label>
        <textarea name="description" id="description"></textarea>
    </div>
    <div>
        <label for="beddings">Nombre de couchage :</label>
        <input type="number" name="beddings" id="beddings">
    </div>
    <div>
        <label for="city">Ville :</label>
        <input type="text" name="city" id="city">
    </div>
    <div>
        <label for="country">Pays :</label>
        <input type="text" name="country" id="country">
    </div>
    <div>
        <label for="typeLogement">Type de logement :</label>
        <select name="typeLogementId" id="typeLogement">
            <?php $types = RepoManager::getRM()->getTypeLogementRepo()->getAll();
                foreach($types as $type) {
                    echo "<option value='" . $type->getId() . "'>" . $type->getName() . "</option>";
                } ?>
        </select>
    </div>
    <div>
        <button type="submit">Ajouter</button>
    </div>
</form>