<!-- Page affichant les détails d'une location -->

<?php

use App\Session;

?>

<h1><?php printf( 'Location : %s', $rental->getTitle() ); ?></h1>

<div class="container-body post-rental">
    <div class="rental-info">
        <ul>
            <li><?php printf( 'Prix : %s € / nuit', $rental->getPrice() ); ?></li>
            <li><?php printf( 'Surface : %s m²', $rental->getSurface() ); ?></li>
            <li><?php printf( 'Description : %s', $rental->getDescription() ); ?></li>
            <li><?php printf( 'Nombre de couchage(s) : %s', $rental->getBeddings() ); ?></li>
        </ul>
    </div>
    <?php if ( $auth::isAuth() && $rental->getOwnerId() == Session::get( Session::USER )->getId() ): ?>
        <div class="button">
            <a href="<?php printf( '/rentals/%s/delete', $rental->getId() ) ?>"> Supprimer</a>
        </div>
    <?php endif;
    
    if ( $auth::isAuth() ):
        if ( $rental->getOwnerId() != Session::get( Session::USER )->getId() ): ?>
            <div class="button">
                <a href="/reservations/add?id=<?php echo $rental->getId() ?>">Réserver</a>
            </div>
        <?php endif;
    endif; ?>
</div>