<header>
    <div>
        <a href="/inscription">Créer un compte</a>
    </div>
    <div>
        <a href="/login">Se connecter</a>
    </div>
</header>
<main>
    <h1>Accueil</h1>

    <h2>Liste des biens disponibles</h2>
    <?php if (!empty($rentals)): ?>
        <ul>
            <?php foreach ($rentals as $rental): ?>
                <a href="/rental/<?php echo $rental->getId() ?>">
                    <?php echo $rental->getDescription() ?>
                </a>
            <?php endforeach ?>
            <br>
        </ul>
    <?php else: ?>
        <div>Aucun bien proposé.</div>
    <?php endif ?>
</main>