<?php

use App\Model\Entity\User;
use App\Session;

?>

<h1>Accueil</h1>

<?php if ($auth::isAuth()):
    if (Session::get(Session::USER)->getTypeAccount() == User::ROLE_OWNER): ?>
        <div class="button">
            <a href="/rentals/add">Ajouter une location</a>
        </div>
        <div>
            <h2>Locations mise en ligne :</h2>
        </div>
    <?php else: ?>
        <div>
            <h2>Liste des biens disponibles :</h2>
        </div>
    <?php endif;
endif;

if (!empty($rentals)): ?>
    <div class="rentals-list">
        <?php foreach ($rentals as $rental): ?>
            <div class="post-rental">
                <a href="/rentals/<?php echo $rental->getId() ?>">
                    Titre : <?php echo $rental->getTitle() ?><br>
                    Adresse : <?php echo $rental->getAddress()->getCity() . " - " . $rental->getAddress()->getCountry() ?><br>
                </a>
            </div>
        <?php endforeach ?>
    </div>
<?php else: ?>
    <div>Aucun bien proposé.</div>
<?php endif ?>