<!-- Page de création d'une réservation par un utilisateur -->

<div>
    <a href="<?php echo $_SERVER['HTTP_REFERER']; ?>">↩ Retour</a>
</div>

<h1>Faire une réservation pour : <?php echo $rental->getTitle() ?></h1>

<div class="container-body">

    <!-- Gestion des messages d'erreur -->
    <?php if (isset($_GET['error'])): ?>
        <div class="error-message">
            <p class="error"><?php echo $_GET['error'] ?></p>
        </div>
    <?php endif; ?>

    <!-- formulaire de réservation -->
    <form action="/reservations/add/<?php echo $rental->getId() ?>" id="form-create-reservation" method="post">
        <fieldset>
            <legend>Informations sur la réservation : </legend>
            <div>
                <label for="dateStart">Date de début :</label>
                <input type="datetime-local" name="dateStart" id="dateStart">
            </div>
            <div>
                <label for="dateEnd">Date de fin :</label>
                <input type="datetime-local" name="dateEnd" id="dateEnd">
            </div>
        </fieldset>
        <div class="button">
            <button type="submit">Réserver</button>
        </div>
    </form>
</div>