<!-- Page d'affichage de la liste des réservations d'un utilisateur -->
<!-- S'il est connecté en tant qu'utilisateur, il voit la liste de ses réservations -->
<!-- S'il est connecté en tant qu'annonceur, il voit la liste des réservations de ses biens -->

<h1>Réservations</h1>

<div class="container-body">
    <h2>Détail de la réservation</h2>

    <div class="list-reservations">
        <div class="post-rental">
            <div class="title-small"><a href="/rentals/<?php echo $reservation->getRental()->getId() ?>"><?php echo $reservation->getRental()->getTitle(); ?></a></div>
            <div>
                <a href="/<?php echo $reservation->getRental()->getImage() ?>"><img class="rental-picture" src="/<?php echo $reservation->getRental()->getImage() ?>" alt="Photo de la location"></a>
            </div>
            <div><?php echo $tools::formatDate($reservation->getStringDateStart()) ?> - <?php echo $tools::formatDate($reservation->getStringDateEnd()); ?></div>
            <?php if ($user->getTypeAccount() == $userConst['ROLE_OWNER']): ?>
                <div><?php echo "Fait par : " . $reservation->getUser()->getFirstName() . " " . $reservation->getUser()->getLastName(); ?></div>
            <?php endif; ?>
            <?php if ($auth::isAuth() && $reservation->getUserId() == $user->getId()): ?>
                <div class="button">
                    <a href="<?php printf('/reservations/%s/delete', $reservation->getId()) ?>">Supprimer</a>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>