<!-- Page d'affichage de la liste des réservations d'un utilisateur -->
<!-- S'il est connecté en tant qu'utilisateur, il voit la liste de ses réservations -->
<!-- S'il est connecté en tant qu'annonceur, il voit la liste des réservations de ses biens -->

<h1>Réservations</h1>

<div class="container-body">
    <h2>Détail de la réservation</h2>

    <div class="list-reservations">
        <div class="post-rental">
            <a href="/reservations/<?php echo $reservation->getId(); ?>">
                <div><?php echo $reservation->getRental()->getTitle(); ?></div>
                <div><?php echo $reservation->getDateStart() ?> - <?php echo $reservation->getDateEnd(); ?></div>
                <?php if ($user->getTypeAccount() == $userConst['ROLE_OWNER']): ?>
                    <div><?php echo "Fait par : " . $reservation->getUser()->getFirstName() . " " . $reservation->getUser()->getLastName(); ?></div>
                <?php endif; ?>
            </a>
            <?php if ($auth::isAuth() && $reservation->getUserId() == $user->getId()): ?>
                <div class="button">
                    <a href="<?php printf('/reservations/%s/delete', $reservation->getId()) ?>">Supprimer</a>
                </div>
            <?php endif; ?>
        </div>
    </div>

    <?php if ($user->getTypeAccount() == $userConst['ROLE_USER']): ?>
        <div class="button">
            <a href="/reservations/%s/delete">Supprimer la réservation</a>
        </div>
    <?php endif; ?>
</div>