<?php

use App\Model\Repository\RepoManager; ?>

<main>
    <h1>Réservations</h1>

    <a href="/reservations/add">Faire une réservation</a>

    <h2>Mes réservations</h2>

    <?php if (!empty($reservations)): ?>
        <ul>
            <?php foreach ($reservations as $reservation): ?>
                <li>
                    <div class="post-rental">
                        <a href="/rentals/<?php echo $reservation->getRentalId() ?>">
                            <?php echo $reservation->getDateStart() ?> - <?php echo $reservation->getDateEnd() ?>
                            <?php echo RepoManager::getRM()->getRentalRepo()->getbyId($reservation->getRentalId())->getTitle() ?>
                        </a>
                    </div>
                </li>
            <?php endforeach ?>
            <br>
        </ul>
    <?php else: ?>
        <div>Aucune réservation.</div>
    <?php endif ?>
</main>