<!-- Page d'affichage de la liste des réservations d'un utilisateur -->
<!-- S'il est connecté en tant qu'utilisateur, il voit la liste de ses réservations -->
<!-- S'il est connecté en tant qu'annonceur, il voit la liste des réservations de ses biens -->

<h1>Réservations</h1>

<div class="container-body">
    <?php if ( $user->getTypeAccount() == $userConst[ 'ROLE_USER' ] ): ?>
         <h2>Mes réservations</h2>
    <?php endif; ?>
    
    
    <div class="list-reservations">
        <?php if ( !empty( $reservations ) ): ?>
            <ul>
                <?php foreach ($reservations as $reservation): ?>
                    <li>
                        <div class="post-rental">
                            <a href="/rentals/<?php echo $reservation->getRentalId(); ?>">
                                <div><?php echo $reservation->getDateStart() ?> - <?php echo $reservation->getDateEnd(); ?></div>
                                <div><?php echo $reservation->getRental()->getTitle(); ?></div>
                                <?php if ( $user->getTypeAccount() == $userConst[ 'ROLE_OWNER' ] ): ?>
                                    <div><?php echo "Fait par : " . $reservation->getUser()->getFirstName() . " " . $reservation->getUser()->getLastName(); ?></div>
                                <?php endif; ?>
                            </a>
                            <?php if ( $auth::isAuth() && $reservation->getUserId() == $user->getId() ): ?>
                                <div class="button">
                                    <a href="<?php printf( '/reservations/%s/delete', $reservation->getId() ) ?>">Supprimer</a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </li>
                <?php endforeach; ?>
                <br>
            </ul>
        <?php else: ?>
            <div>Aucune réservation.</div>
        <?php endif; ?>
    </div>

    <?php if ( $user->getTypeAccount() == $userConst[ 'ROLE_USER' ] ): ?>
        <div class="button">
        <a href="/">Faire une réservation</a>            
        </div>
    <?php endif; ?>
</div>