<div>
    <a href="/">🔙 Retour</a>
</div>
<h1>Créer mon compte</h1>

<form action="/registration" id="form-create-user" method="post">

    <!-- gestion des messages d'erreur -->
    <?php if (isset($_GET['error'])): ?>
        <p class="error"><?php echo $_GET['error'] ?></p>
    <?php endif; ?>

    <div>
        <label for="first_name">Prénom</label>
        <input type="text" id="first_name" name="first_name" required>
    </div>
    <div>
        <label for="last_name">Nom</label>
        <input type="text" id="last_name" name="last_name" required>
    </div>
    <div>
        <label for="email">Adresse email</label>
        <input type="email" id="email" name="email" required>
    </div>
    <div>
        <label for="password">Mot de passe</label>
        <input type="password" id="password" name="password" required>
    </div>
    <div>
        <label for="type_compte">Type de compte :</label>
        <select name="type_compte" id="type_compte">
            <option value="1">Annonceur</option>
            <option value="2">utilisateur</option>
        </select>
    </div>
    <button type="submit">Créer mon compte</button>
</form>