<div>
    <a href="/">🔙 Retour</a>
</div>
<h1>Créer mon compte</h1>

<form action="/registration" id="form-create-user" method="post">

    <!-- gestion des messages d'erreur -->
    <?php if (isset($_GET['error'])): ?>
        <p class="error"><?php echo $_GET['error'] ?></p>
    <?php endif; ?>

    <div>
        <label for="firstName">Prénom</label>
        <input type="text" id="firstName" name="firstName">
    </div>
    <div>
        <label for="lastName">Nom</label>
        <input type="text" id="lastName" name="lastName" required>
    </div>
    <div>
        <label for="email">Adresse email</label>
        <input type="email" id="email" name="email" required>
    </div>
    <div>
        <label for="password">Mot de passe</label>
        <input type="password" id="password" name="password" required>
    </div>
    <div>
        <label for="typeAccount">Type de compte :</label>
        <select name="typeAccount" id="typeAccount">
            <option value="1">Annonceur</option>
            <option value="2">Utilisateur</option>
        </select>
    </div>
    <button type="submit">Créer mon compte</button>
</form>