<h1>Créer mon compte</h1>

<form action="/create-account" method="post">
    <div>
        <label for="first_name">Prénom</label>
        <input type="text" id="first_name" name="first_name" required>
    </div>
    <div>
        <label for="last_name">Nom</label>
        <input type="text" id="last_name" name="last_name" required>
    </div>
    <div>
        <label for="email">Adresse email</label>
        <input type="email" id="email" name="email" required>
    </div>
    <div>
        <label for="password">Mot de passe</label>
        <input type="password" id="password" name="password" required>
    </div>
    <button type="submit">Créer mon compte</button>
</form>