<h1>Se connecter</h1>

<!-- gestion des messages d'erreur -->
<?php if (isset($_GET['error'])): ?>
    <p class="error"><?php echo $_GET['error'] ?></p>
<?php endif; ?>

<form action="/login" method="post">
    <div>
        <label for="email">Adresse email</label>
        <input type="email" id="email" name="email" required>
    </div>
    <div>
        <label for="password">Mot de passe</label>
        <input type="password" id="password" name="password" required>
    </div>
    <button type="submit">Se connecter</button>