<div>
    <a href="/admin/users">🔙 Retour</a>
</div>
<h1>Modifier</h1>
<form action="/admin/users/<?php echo $user->getId() ?>" method="post" novalidate>
    <div>
        <label for="input-firstname">Prénom :</label>
        <input type="text" name="firstname" id="input-firstname" value="<?php echo $user->getFirstName() ?>">
    </div>
    <div>
        <label for="input-lastname">Nom :</label>
        <input type="text" name="lastname" id="input-lastname" value="<?php echo $user->getLastName() ?>">
    </div>
    <div>
        <input type="submit" value="Enregistrer la modification">
    </div>
</form>
<div>
    <a href="<?php printf( '/admin/users/%s/delete', $user->getId() ) ?>">❌ Supprimer</a>
</div>