<div class="button">
    <a href="/admin">🏠 Retour</a>
</div>

<h1>Liste des utilisateurs</h1>

<div class="button">
    <a href="/admin/users/add">Ajouter un utilisateur</a>
</div>

<?php if(!empty($users)): ?>
<div>
    <ul>
        <?php foreach( $users as $user ): ?>
            <li>
                <h2>
                    <?php printf(
                        '<a href="/admin/users/%s">%s %s</a>',
                        $user->getId(),
                        $user->getFirstname(),
                        $user->getLastname()
                    ) ?>
                </h2>
                <ul>
                    <li>Id: <?php echo $user->getId() ?></li>
                    <li>Email: <?php echo $user->getEmail() ?></li>
                    <li>Prénom: <?php echo $user->getFirstName() ?></li>
                    <li>Nom: <?php echo $user->getLastName() ?></li>
                </ul>
            </li>
        <?php endforeach ?>
    </ul>
</div>
<?php else: ?>
    <div>Aucun utilisateur inscrit.</div>
<?php endif ?>